# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0bc77fd2eda41943fe205a3393b97008d3dd3d9657459a5c14afce0b95357f71eb70091331cd8c3a401fe17b4ee16b5a520529b67b86a1796edf78b55d527e0b

test:
  secret_key_base: c4994df16cd86ed15e1e5ec50ce739f7d3edb274757c4c9e91f6080d2de7863863c996cfbf325eaf310cc6b419a2483e7cf103c8b04dedeaa14716255df333b5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
